version: '3.8'

services:
  django:
    container_name: sst_django
    build:
      context: .
      dockerfile: ./.docker/local/Dockerfile
    entrypoint: ./.docker/local/entrypoint
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    container_name: sst_postgres
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sst_mvp
      - POSTGRES_PASSWORD=sst_mvp
      - POSTGRES_DB=sst_mvp

volumes:
  postgres_data: { }
