# Generated by Django 5.1.3 on 2024-12-08 13:53

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaborators", "0003_collaborator_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collaborator",
            name="last_checkup",
        ),
        migrations.RemoveField(
            model_name="collaborator",
            name="next_checkup",
        ),
        migrations.RemoveField(
            model_name="collaborator",
            name="status",
        ),
        migrations.AddField(
            model_name="collaborator",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collaborator",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime(2024, 12, 8, 13, 52, 42, 893899, tzinfo=datetime.timezone.utc)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collaborator",
            name="end_date",
            field=models.DateField(blank=True, help_text="Date when the collaborator stopped working", null=True),
        ),
        migrations.AddField(
            model_name="collaborator",
            name="identification_number",
            field=models.CharField(default=1234, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collaborator",
            name="phone_number",
            field=models.CharField(default=1234567, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collaborator",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2024, 12, 8, 13, 53, 5, 404354, tzinfo=datetime.timezone.utc),
                help_text="Date when the collaborator started working",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collaborator",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="subordinates",
                to="collaborators.collaborator",
            ),
        ),
    ]
