# Generated by Django 5.1.3 on 2024-11-29 22:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("collaborators", "0003_collaborator_status"),
        ("organizations", "0003_rename_organizationrol_organizationrole"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentType",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("incident_date", models.DateField()),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(choices=[("CLOSED", "Closed"), ("OPEN", "Open")], default="OPEN", max_length=20),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")], default="LOW", max_length=20
                    ),
                ),
                (
                    "collaborator",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="collaborators.collaborator"),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="organizations.organization"),
                ),
                (
                    "incident_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="incidents.incidenttype"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
