# Generated by Django 5.1.3 on 2024-11-29 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0001_initial"),
        ("organizations", "0003_rename_organizationrol_organizationrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidenttype",
            name="organization",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.DO_NOTHING, to="organizations.organization"
            ),
            preserve_default=False,
        ),
    ]
