# Generated by Django 5.1.3 on 2024-12-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_incidenttype_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[("CLOSED", "Closed"), ("OPEN", "Open"), ("IN_PROGRESS", "In Progress")],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
