# Generated by Django 5.1.3 on 2024-12-08 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_rename_organizationrol_organizationrole"),
        ("users", "0006_create_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="users",
            field=models.ManyToManyField(through="users.UserOrganization", to=settings.AUTH_USER_MODEL),
        ),
    ]
