# Generated by Django 5.1.3 on 2024-12-08 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_rename_organizationrol_organizationrole"),
        ("users", "0003_historicaluserorganization_userorganization_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userorganization",
            unique_together={("user", "organization")},
        ),
    ]
