# Generated by Django 5.1.3 on 2024-12-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0004_alter_userorganization_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorganization",
            name="groups",
            field=models.ManyToManyField(to="auth.group"),
        ),
    ]
