# Generated by Django 5.1.3 on 2024-12-08 22:46

from django.db import migrations, models


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    # Create the groups
    profesional_sst, created = Group.objects.get_or_create(name="ProfesionalSST")
    analista_sst, created = Group.objects.get_or_create(name="AnalistaSST")
    operador, created = Group.objects.get_or_create(name="Operador")


def remove_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    # Create the groups
    Group.objects.filter(name__in=["ProfesionalSST", "AnalistaSST", "Operador"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userorganization_groups"),
    ]

    operations = [migrations.RunPython(create_groups, reverse_code=remove_groups)]
