# Generated by Django 5.1.3 on 2024-12-08 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organizations", "0004_organization_users"),
        ("users", "0006_create_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="organizations",
        ),
        migrations.AlterField(
            model_name="userorganization",
            name="groups",
            field=models.ManyToManyField(blank=True, null=True, to="auth.group"),
        ),
        migrations.AlterField(
            model_name="userorganization",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_organizations",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="userorganization",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
